### ISSUE TITLE
Support style mixin

### ISSUE THREAD

**Issue by zoechi** [PolymerElements/iron-icon#47]
I want to use the Fontawesome SVG fonts icons using a iron-iconset-svg and need to set a few CSS settings like
- `font-family`
- `font-size`
- `dominant-baseline`
- `text-anchor`
  Currently only width and height are supported

I want to get rid of the `/deep/` in this CSS

``` css
  * /deep/ core-icon text.bwu-fa-icon {
    font-family: "FontAwesome";
    font-size: 24px;
    dominant-baseline: central;
    text-anchor: middle;
  }
```

Full example at https://github.com/bwu-dart/bwu_fontawesome_iconset_svg/blob/master/lib/bwu_fontawesome_iconset_svg.html#L15

In my case icons are SVG font glyphs.
