### ISSUE TITLE
changing color doesn't work as documented

### ISSUE THREAD

**Issue by nylki** [PolymerElements/iron-icon#55]
The [documentation](https://github.com/PolymerElements/iron-icon#styling) says: 

``` .css
    --iron-icon-fill-color: green
```

However this doesn't seem to work on my side ( "polymer": "~1.2.1", "iron-elements": "~1.0.4").
Also the width/height change attributes don't seem to take effect.

html:

``` .html
<iron-selector id="tool-box" attr-for-selected="name" selected="polygon">
    <iron-icon class="tool-box-icon" name="polygon" src="images/IconTool_BLACK/IconTools_Path_black.svg"></iron-icon>
    <iron-icon class="tool-box-icon" name="compare" src="images/IconTool_BLACK/IconTools_Compare_black.svg"></iron-icon>
    <iron-icon class="tool-box-icon" name="freehand" src="images/IconTool_BLACK/IconTools_Brush_black.svg"></iron-icon>
    <iron-icon class="tool-box-icon" name="text" src="images/IconTool_BLACK/IconTools_Text_black.svg"></iron-icon>
</iron-selector>

```

css:

``` .css
.tool-box-icon .iron-selected {

  --iron-icon-fill-color: white;
}

.tool-box-icon *:not(.iron-selected):hover {

    --iron-icon-fill-color: blue;

}
```

**Comment by notwaldorf** [comment]
It would be great if you could reproduce this in a jsbin, however just by looking at your code, I think you aren't using the correct css selector for custom properties. It should use the custom element you are targetting, so something like:

``` css
iron-icon.tool-box-icon .iron-selected {
  --iron-icon-fill-color: white;
}

iron-icon.tool-box-icon *:not(.iron-selected):hover {
   --iron-icon-fill-color: blue;
}
```

Also make sure all of these are in a `<style is="custom-style">` tag.
