### ISSUE TITLE
Add mixin to style img tag when src is defined

### ISSUE THREAD

**Issue by motss** [PolymerElements/iron-icon#84]
### Description
Not able to style the `<img>` tag inside `iron-icon`. It would be helpful for use case where a `paper-icon-button` can be created with rounded corner.

**Comment by tony19** [comment]
Use this style:

```css
paper-icon-button {
  width: 64px;
  height: 64px;
  --iron-icon: {
    border-radius: 50%;
    overflow: hidden;  /* hide overflow of underlying image */
  };
}
```

[codepen](http://codepen.io/tony19/pen/XNMJXL?editors=1000)
