### ISSUE TITLE
[0.9] Sizing not applied from classes

### ISSUE THREAD

**Issue by dhpollack** [PolymerElements/iron-icon#9]
In 0.9.0-rc.1, iron-icons can no longer be styled via a CSS class.  For some reason, the ".-iron-icon-0" class is always applied to the icon with a height and width of 24px.

**Comment by mwinters-stuff** [comment]
I am seeing this too..

This is from the iron-iconset-svg demo..

iron-icon.iron-icon-0 {
  width: 24px;
  height: 24px;
  ~~display: -ms-inline-flexbox;~~
 ~~ display: -webkit-inline-flex;~~
  display: inline-flex;
 ~~ -ms-flex-align: center;~~
~~  -webkit-align-items: center;~~
  align-items: center;
  ~~-ms-flex-pack: center;~~
 ~~ -webkit-justify-content: center;~~
  justify-content: center;
}
iron-icon:nth-of-type(2) {
  fill: green;
  stroke: orange;
}
iron-icon {
 ~~ transition: all 0.5s;~~
  -webkit-transition: all 0.5s;
}
iron-icon {
  ~~height: 128px;~~
  ~~width: 128px;~~
}
iron-icon {
  position: relative;
  vertical-align: middle;
  fill: currentcolor;
  ~~width: var(--iron-icon-size);~~
  ~~~~height: var(--iron-icon-size);~~
}

**Comment by dhpollack** [comment]
To update this issue, you can style things via the <style is="custom-style"> </style> tag, but that doesn't propogate downwards which is annoying.  So if I use the iron-icon element in multiple custom elements and I want them all to be the same size, then I have to add that custom-style to each individual custom element instead of just setting it once in a CSS file and then applying a custom style to the iron-icon.

This seems to be by design, but I'm baffled as to why one would want it this way.  It is a lot more logical that setting the style in a CSS file should override the default style of the element.

**Comment by kevinpschaaf** [comment]
`iron-icon` exposes a [custom-property API](https://github.com/PolymerElements/iron-icon/blob/master/iron-icon.html#L66) for sizing the icon, so you can do something like this in an element's stylesheet (or in a `<style is="custom-style">` from the main document:

```
:root {
  --iron-icon-width: 64px;
  --iron-icon-height: 64px;
}
```

Since custom properties inherit, you don't need to define this everywhere you use an icon, you can define it at the top of a tree and it will apply to all icons below that point.

Since `iron-icon` exposes an explicit inheriting custom property API for defining height/width, you should use these rather than `height` and `width` properties directly.

**Comment by mwinters-stuff** [comment]
The documentation appears updated, the example in the documentation needs to change then.

**Comment by dhpollack** [comment]
@kevinpschaaf @wintersandroid so my question is if you use ":root" to change the size of iron-icons, how would one put two different sized iron icons into the same app?  Previously, I just used normal css styles to apply one style to "small" icons and another to "big" icons, but now that doesn't seem possible.

**Comment by kevinpschaaf** [comment]
The `:root` example was answering this use case:

> So if I use the iron-icon element in multiple custom elements and I want them all to be the same size

You can also use custom properties in rules that target custom elements in a given scope, just like normal css properties:

``` css
.big {
  --iron-icon-width: 64px;
  --iron-icon-height: 64px;
}
.small {
  --iron-icon-width: 32px;
  --iron-icon-height: 32px;
}
```

``` html
<iron-icon class="big"></iron-icon>
<iron-icon class="small"></iron-icon>
```

Just be aware of some of the limitations of the custom property shim, which are discussed here: https://www.polymer-project.org/1.0/docs/devguide/styling.html#custom-properties-shim---limitations-and-api-details

**Comment by dhpollack** [comment]
for some reason that never seems to work for me.  Instead the 24px size is always applied and the class size is ignored.

**Comment by kevinpschaaf** [comment]
Just made a jsBin to confirm this should work:
- Icons in a custom element: http://jsbin.com/qadugo/1/edit
- Icons in the main document: http://jsbin.com/natefi/2/edit

Again per the caveats of the shim discussed [here](https://www.polymer-project.org/1.0/docs/devguide/styling.html#custom-properties-shim---limitations-and-api-details), if you change a class on an element that would cause it to consume a different custom property, you need to call `this.updateStyles()` on the host of the element (or `Polymer.updateStyles()` if the element is in the main document) to re-evaluate custom properties.

If you can construct a problematic repro case, that shows where you're having trouble, we'd be happy to help.

**Comment by notwaldorf** [comment]
apply label: pending response

**Comment by cyraid** [comment]
Using "paper-button" and "iron-icon" inside of it.. I'm gonna say I'm with @dhpollack on this one.. Nothing anyone's mentioned except:

``` css
<style is="custom-style">
  paper-button iron-icon {
    width  : 32px;
    height : 32px;
  }
</style>
```

**Comment by yglodt** [comment]
With 1.0.3 none of the above work.
Note that I am using a custom svg icon <iron-icon class="big" src="/resources/myicon.svg"></iron-icon>

Edit: This works:

  iron-icon.iron-icon-0 {
   height: 64px;
   width: 64px;
  }

**Comment by notwaldorf** [comment]
This issue is old, and doesn't have any repro steps. If anyone can create a jsbin with repro steps, I'll gladly reopen this and look at it. In the meantime, an updated TL; DR:

To resize a particular `iron-icon`:

``` css
<style is="custom-style">
  iron-icon.big {
     --iron-icon-height: 50px;
     --iron-icon-width: 50px;
  }
</style>
```

To resize all the `iron-icon`s on this page:

``` css
<style is="custom-style">
  iron-icon {
     --iron-icon-height: 50px;
     --iron-icon-width: 50px;
  }
</style>
```

To resize all the `iron-icons` in the app, including nested ones in custom elements:

``` css
<style is="custom-style">
  :root {
     --iron-icon-height: 50px;
     --iron-icon-width: 50px;
  }
</style>
```

Hope this helps!
